import { library } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

// Solid icons
import {
  faMagnifyingGlass,
  faXmark,
  faUser,
  faArrowRightFromBracket,
  faHeart,
  faBagShopping,
  faBars,
  faCartShopping,
  faCartPlus,
  faSliders,
  faChevronUp,
  faFilter,
  faBoxOpen,
  faEnvelope,
  faPills,
  faCircleExclamation,
  faCheck,
  faSpinner,
  faArrowLeftLong,
  faLocationDot,
  faPhone,
  faTruck,
  faShieldHalved,
  faUserDoctor,
  faClock,
  faPill,
  faHeartCirclePlus,
  faBaby,
  faSparkles,
  faStethoscope,
  faShieldCheck,
  faArrowRight,
  faCartArrowDown,
  faMinus,
  faPlus,
  faTag,
  faCircleCheck,
  faFileLines,
  faTruckFast,
  faLock,
  faShield,
  faTriangleExclamation,
  faClipboardCheck,
  faCreditCard,
  faBuildingColumns,
  faMobileScreen,
  faArrowLeft,
} from "@fortawesome/free-solid-svg-icons";

// Regular icons
import {
  faHeart as faHeartRegular,
  faUser as faUserRegular,
  faEnvelope as faEnvelopeRegular,
  faClock as faClockRegular,
  faFileLines as faFileLinesRegular,
} from "@fortawesome/free-regular-svg-icons";

// Brand icons
import { faInstagram } from "@fortawesome/free-brands-svg-icons";

library.add(
  faMagnifyingGlass,
  faXmark,
  faUser,
  faArrowRightFromBracket,
  faHeart,
  faBagShopping,
  faBars,
  faCartShopping,
  faCartPlus,
  faSliders,
  faChevronUp,
  faFilter,
  faBoxOpen,
  faEnvelope,
  faPills,
  faCircleExclamation,
  faCheck,
  faSpinner,
  faArrowLeftLong,
  faLocationDot,
  faPhone,
  faTruck,
  faShieldHalved,
  faUserDoctor,
  faClock,
  faPill,
  faHeartCirclePlus,
  faBaby,
  faSparkles,
  faStethoscope,
  faShieldCheck,
  faArrowRight,
  faCartArrowDown,
  faMinus,
  faPlus,
  faTag,
  faCircleCheck,
  faFileLines,
  faTruckFast,
  faLock,
  faShield,
  faTriangleExclamation,
  faClipboardCheck,
  faCreditCard,
  faBuildingColumns,
  faMobileScreen,
  faArrowLeft,
  faHeartRegular,
  faUserRegular,
  faEnvelopeRegular,
  faClockRegular,
  faFileLinesRegular,
  faInstagram
);

export { FontAwesomeIcon };